stages:
  train:
    cmd: python train.py
    deps:
    - mushrooms.csv
    - train.py
    outs:
    - metrics.txt
    - rf.pkl
    metrics:
    - scores.json
    plots:
    - prc.json:
        cache: false
        x: recall
        y: precision
    - roc.json:
        cache: false
        x: fpr
        y: tpr
    params:
    - train.max_depth
    - train.n_estimators
    - train.seed
